projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - schema.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ../types/API.ts
        docsFilePath: .
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: none
        maxDepth: 10
extensions:
  amplify:
    version: 3
